# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ct < Formula
  desc "Easy commit templates."
  homepage "https://github.com/iamlucasvieira/ComTemplate"
  version "0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iamlucasvieira/ComTemplate/releases/download/v0.3/ct_Darwin_arm64.tar.gz"
      sha256 "673c62812951146868906ddebcfe49fbafd61df645388534ab16799495cbd87f"

      def install
        bin.install "ct"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/ComTemplate/releases/download/v0.3/ct_Darwin_x86_64.tar.gz"
      sha256 "30ea05bd887bfe8fa0eedf95dc3e2ce8aca89275dc258b1ffe2f81873f663468"

      def install
        bin.install "ct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamlucasvieira/ComTemplate/releases/download/v0.3/ct_Linux_arm64.tar.gz"
      sha256 "59612bb932f277a3f5be5740545faae6fb3eafe5be50d18fc32828a8d492a5ce"

      def install
        bin.install "ct"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/ComTemplate/releases/download/v0.3/ct_Linux_x86_64.tar.gz"
      sha256 "17b548accc33621ff0a651920283765046b1eceb453affdfcc05c0a179b09fcb"

      def install
        bin.install "ct"
      end
    end
  end
end
