# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ct < Formula
  desc "Easy commit templates."
  homepage "https://github.com/iamlucasvieira/hnews"
  version "1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iamlucasvieira/ComTemplate/releases/download/v1.0/ComTemplate_Darwin_arm64.tar.gz"
      sha256 "39940ce232e8cf8aae6f64ea8e321bf6e5b7d9554e77cf7b20ab0df6c105c662"

      def install
        bin.install "ComTemplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/ComTemplate/releases/download/v1.0/ComTemplate_Darwin_x86_64.tar.gz"
      sha256 "f557882d3987137df1fe277f29d05dc165b4590eb2f69e92164ac7ea47395168"

      def install
        bin.install "ComTemplate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamlucasvieira/ComTemplate/releases/download/v1.0/ComTemplate_Linux_arm64.tar.gz"
      sha256 "c83e0d71d6238d320613280286932591f88bafcc0f2d3f5d951b070dcdcd950b"

      def install
        bin.install "ComTemplate"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/ComTemplate/releases/download/v1.0/ComTemplate_Linux_x86_64.tar.gz"
      sha256 "d7a422fc36fb6af61c5597b174306b7d71be89aeecfcc318c5baeb9e63f474e5"

      def install
        bin.install "ComTemplate"
      end
    end
  end
end
