# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hnews < Formula
  desc "Hacker News in your terminal"
  homepage "https://github.com/iamlucasvieira/hnews"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/hnews/releases/download/v0.1.0/hnews_Darwin_x86_64.tar.gz"
      sha256 "acd28a8140b32ab9b05ef9877f21f1e21bd55609fdd30b3a860182ea0f039fd6"

      def install
        bin.install "hnews"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iamlucasvieira/hnews/releases/download/v0.1.0/hnews_Darwin_arm64.tar.gz"
      sha256 "6f4e553281fbda03ad30737f8a9a27d07c2f6f1c719c88875fa486f347fbdc41"

      def install
        bin.install "hnews"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamlucasvieira/hnews/releases/download/v0.1.0/hnews_Linux_arm64.tar.gz"
      sha256 "82c5d4bfe5a5737f837bb210d13995aab5bf5ef38505af4ecbe657b14c4ae2e5"

      def install
        bin.install "hnews"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/hnews/releases/download/v0.1.0/hnews_Linux_x86_64.tar.gz"
      sha256 "b86086461a9ecdfe58be5352362aaa24546c4a6f872d695c6bbcc2068a431a87"

      def install
        bin.install "hnews"
      end
    end
  end
end
