# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hnews < Formula
  desc "My resume in CLI version>"
  homepage "https://github.com/iamlucasvieira/my-resume-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.1.0/my-resume-cli_Darwin_arm64.tar.gz"
      sha256 "fa3e6d3045072c9602d436639a7cca8f7065669c4fbd3d405c9dc7b03cade860"

      def install
        bin.install "my-resume-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.1.0/my-resume-cli_Darwin_x86_64.tar.gz"
      sha256 "c02355a1d41fd3f9fed00376ae881e3edad9dcadd3bb2e5dcaf56ddc634ddcc5"

      def install
        bin.install "my-resume-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.1.0/my-resume-cli_Linux_x86_64.tar.gz"
      sha256 "85a07467ba5b03494357041c19801d1ba8c45bd0b43d460778567a4112efcb6f"

      def install
        bin.install "my-resume-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.1.0/my-resume-cli_Linux_arm64.tar.gz"
      sha256 "c59f84016c23b71987f5dd663cf2a610bd70c9fc37d5a8e794ea8cb2bc0df5b3"

      def install
        bin.install "my-resume-cli"
      end
    end
  end
end
