# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hnews < Formula
  desc "My resume in CLI version>"
  homepage "https://github.com/iamlucasvieira/my-resume-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.1.0/lucas-cli_Darwin_arm64.tar.gz"
      sha256 "3c34e756b19ff88922c6eb4c39a3c7aae107e9bf0371ccb87c67796f7f362e61"

      def install
        bin.install "lucas-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.1.0/lucas-cli_Darwin_x86_64.tar.gz"
      sha256 "61fd10dc31ab955a8eeb911de4a0c1b250657b912421f9401b1c215faca95b6c"

      def install
        bin.install "lucas-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.1.0/lucas-cli_Linux_arm64.tar.gz"
      sha256 "81d9f4912c73337cebda6d1a8bfa120baaddd6b0eb4d538022600a2834138331"

      def install
        bin.install "lucas-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.1.0/lucas-cli_Linux_x86_64.tar.gz"
      sha256 "318b975d8ea764211b2ef4847080c4c66620e7428f88f023f56c44a29390b75e"

      def install
        bin.install "lucas-cli"
      end
    end
  end
end
