# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LucasCli < Formula
  desc "My resume in CLI version>"
  homepage "https://github.com/iamlucasvieira/my-resume-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.2.0/lucas-cli_Darwin_arm64.tar.gz"
      sha256 "7522572cc1aae755362a0cf9ae32bc9dcd735a7c7176cc40d72c3891949aa44c"

      def install
        bin.install "lucas-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.2.0/lucas-cli_Darwin_x86_64.tar.gz"
      sha256 "711fbcb223cc432d18646163acc32e9c03ac1cb52599d95fb6e7f1ed7fb56e8c"

      def install
        bin.install "lucas-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.2.0/lucas-cli_Linux_x86_64.tar.gz"
      sha256 "acc419802847bb4d87c50000246cb58fe81bd81e4409e45796f422ef784f7dfd"

      def install
        bin.install "lucas-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iamlucasvieira/my-resume-cli/releases/download/v0.2.0/lucas-cli_Linux_arm64.tar.gz"
      sha256 "3c132b64a28b37a70f31d5ae8ce3940b9094de422e6663877d95f6a69cbde8a6"

      def install
        bin.install "lucas-cli"
      end
    end
  end
end
